#include<bits/stdc++.h>
using namespace std;
int main(){
string x;
cin>>x;
if(x.size()==1){
    if(x[0]=='0'){
        cout<<"zero";
        }
    if(x[0]=='1'){
        cout<<"one";
        }
    if(x[0]=='2'){
        cout<<"two";
        }
    if(x[0]=='3'){
        cout<<"three";
        }
    if(x[0]=='4'){
        cout<<"four";
        }
    if(x[0]=='5'){
        cout<<"five";
        }
    if(x[0]=='6'){
        cout<<"six";
        }
    if(x[0]=='7'){
        cout<<"seven";
        }
    if(x[0]=='8'){
        cout<<"eight";
        }
    if(x[0]=='9'){
        cout<<"nine";
        }
    }

else if(x.size()==2){
    if(x[0]=='1'){
    if(x[1]=='0'){
        cout<<"ten";
        }
    if(x[1]=='1'){
        cout<<"eleven";
    }
    if(x[1]=='2'){
        cout<<"twelve";
    }
    if(x[1]=='3'){
        cout<<"thirteen";
    }
    if(x[1]=='4'){
        cout<<"fourteen";
    }
    if(x[1]=='5'){
        cout<<"fifteen";
    }
    if(x[1]=='6'){
        cout<<"sixteen";
    }
    if(x[1]=='7'){
        cout<<"seventeen";
    }
    if(x[1]=='8'){
        cout<<"eighteen";
    }
    if(x[1]=='9'){
        cout<<"nineteen";
    }
    }
    else{
        if(x[0]=='2'&&x[1]!='0'){
            cout<<"twenty-";
        }
        if(x[0]=='3'&&x[1]!='0'){
            cout<<"thirty-";
        }
        if(x[0]=='4'&&x[1]!='0'){
            cout<<"forty-";
        }
        if(x[0]=='5'&&x[1]!='0'){
            cout<<"fifty-";
        }
        if(x[0]=='6'&&x[1]!='0'){
            cout<<"sixty-";
        }
        if(x[0]=='7'&&x[1]!='0'){
            cout<<"seventy-";
        }
        if(x[0]=='8'&&x[1]!='0'){
            cout<<"eighty-";
        }
        if(x[0]=='9'&&x[1]!='0'){
            cout<<"ninety-";
        }
        if(x[1]=='1'){
        cout<<"one";
        }
    if(x[1]=='2'){
        cout<<"two";
        }
    if(x[1]=='3'){
        cout<<"three";
        }
    if(x[1]=='4'){
        cout<<"four";
        }
    if(x[1]=='5'){
        cout<<"five";
        }
    if(x[1]=='6'){
        cout<<"six";
        }
    if(x[1]=='7'){
        cout<<"seven";
        }
    if(x[1]=='8'){
        cout<<"eight";
        }
    if(x[1]=='9'){
        cout<<"nine";
        }
        if(x[0]=='2'&&x[1]=='0'){
            cout<<"twenty";
        }
        if(x[0]=='3'&&x[1]=='0'){
            cout<<"thirty";
        }
        if(x[0]=='4'&&x[1]=='0'){
            cout<<"forty";
        }
        if(x[0]=='5'&&x[1]=='0'){
            cout<<"fifty";
        }
        if(x[0]=='6'&&x[1]=='0'){
            cout<<"sixty";
        }
        if(x[0]=='7'&&x[1]=='0'){
            cout<<"seventy";
        }
        if(x[0]=='8'&&x[1]=='0'){
            cout<<"eighty";
        }
        if(x[0]=='9'&&x[1]=='0'){
            cout<<"ninety";
        }
    }
}
cout<<endl;
}
